# Generated by Django 4.0.5 on 2022-06-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_familiar', models.CharField(max_length=50)),
                ('edad_familiar', models.IntegerField()),
                ('nacimiento_familiar', models.DateField(null=True)),
            ],
        ),
    ]
